/**
 * Secrets manager API
 * An API to manage a list of secrets. Each secret has a name and id and its secret text. Using the API you can add a secret and list all secrets and show the secret text.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * The data for a new secret
 */
export interface NewSecret {
  /**
   * A name that would allow to identify the secret. This will be shown in cleartext to the user
   */
  name: string;
  /**
   * Our application supports exporting data to files but sometimes for really secret stuff we want to disable this, so,
   * here, the user can tell the app to never allow to export this secret to file. defaults to false
   */
  allowExport?: boolean;
  /**
   * The secret text
   */
  text: string;

}
