/**
 * Secrets manager API
 * An API to manage a list of secrets. Each secret has a name and id and its secret text. Using the API you can add a secret and list all secrets and show the secret text.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {NewSecret} from './newSecret';


/**
 * An existing secret which is already stored in db
 */
export interface Secret extends NewSecret {
  id: string;
  createdAt: Date;
}
